@startuml
skinparam classAttributeIconSize 0

' Interface principal
interface JSONValue {
    +toJSONString(): String
    +accept(visitor: JsonVisitor)
}

' Tipos primitivos
class JSONString {
    -value: String
}

class JSONNumber {
    -value: Number
}

class JSONBoolean {
    -value: Boolean
}

class JSONNull

' Tipos compostos
class JSONArray {
    -elements: List<JSONValue>
    +map(transform): JSONArray
    +filter(predicate): JSONArray
}

class JSONObject {
    -properties: Map<String, JSONValue>
    +filter(predicate): JSONObject
}

' Visitor
interface JsonVisitor {
    +visitString(value: JSONString)
    +visitNumber(value: JSONNumber)
    +visitBoolean(value: JSONBoolean)
    +visitNull()
    +visitArray(value: JSONArray)
    +visitObject(value: JSONObject)
}

' Heranças (implementa JSONValue)
JSONString ..|> JSONValue
JSONNumber ..|> JSONValue
JSONBoolean ..|> JSONValue
JSONNull ..|> JSONValue
JSONArray ..|> JSONValue
JSONObject ..|> JSONValue

' JSONObject e JSONArray usam JSONValue
JSONObject "1" o-- "*" JSONValue
JSONArray "1" o-- "*" JSONValue

' JSONValue aceita JsonVisitor
JSONValue ..> JsonVisitor : accept()

@enduml
